name: Testing pipeline

on:
  pull_request:
    branches:
      - main
      - addedUnitTest
  push:
    branches:
      - main
      - addedUnitTest

permissions:
  contents: 'read'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.7.1
        poetry install
    - name: Run linters
      run: make lint-check

    - name: Run unit-tests
      run: make unit-tests

# Set Node.js version to 18 for running Cypress and npm commands
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Cypress
      working-directory: tests/e2e_tests
      run: |
        npm install cypress

# Run all Cypress tests using default config
    - name: Run Cypress tests
      working-directory: tests/e2e_tests/e2e
      run: npx cypress run --spec "cypress/e2e/**/*"

    - name: Run Flask server in background
      run: |
        poetry run flask run &
        echo $! > flask_pid.txt
        sleep 3

# Run Cypress tests specifying the folder with your test specs
    - name: Run Cypress tests
      run: npx cypress run --spec "tests/e2e_tests/cypress/e2e/**/*"

# Stop the Flask server using the saved process ID
    - name: Stop Flask server
      run: kill $(cat flask_pid.txt)


    # - name: Run tests with coverage
    #   run: make coverage
    # - name: Coveralls
    #   uses: coverallsapp/github-action@v1
    #   with:
    #     path-to-lcov: "./coverage.lcov"
    #     github-token: ${{ secrets.GITHUB_TOKEN }}

